name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    name: build

    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache wasm-bindgen
      uses: actions/cache@v4
      id: cache-wasm-bindgen
      with:
        path: ~/.cargo/bin/wasm-bindgen
        key: ${{ runner.os }}-wasm-bindgen-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-wasm-bindgen-

    - name: Install wasm-bindgen
      if: steps.cache-wasm-bindgen.outputs.cache-hit != 'true'
      run: cargo install wasm-bindgen-cli

    - name: Cache Cargo
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          out/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build binary (windows)
      run: cargo build --verbose --release
      env:
          RUST_BACKTRACE: 1

    - name: Build wasm
      run: |
        rustup target add wasm32-unknown-unknown
        cargo build --verbose --target wasm32-unknown-unknown --release
        wasm-bindgen --no-typescript --target web --out-dir ./out/ --out-name "hello-bevy" ./target/wasm32-unknown-unknown/release/hello-bevy.wasm

    - name: Build archive
      shell: bash
      run: |
        mkdir archive
        cp README.md archive/
        cp -r assets/ out/assets/
        cp -r out/ archive/wasm32/
        tar acvf archive/wasm32.zip archive/wasm32/
        mkdir archive/windows
        cp target/release/hello-bevy.exe archive/windows/
        cp -r assets/ archive/windows/
        tar acvf archive/windows.zip archive/windows/

    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: archive/
        compression-level: 0